### ISSUE TITLE
Can filters be bi-directional in Vega Vis ?

### ISSUE THREAD

**Issue by sriharshaanp** [nyurik/kibana-vega-vis#63] opened 2018-04-23 23:50 UTC
Hi, 
I am trying to create a map visualization in Kibana using Vega Vis by overlaying the geographic points on the Kibana default map. I am trying to get the filters in the Kibana dashboard to change based on a selection of a certain object/ point on the map and also affect the other graphs on the dashboard. Can you let me know if this can be done in any way?

Thanks and Regards

**Comment by nyurik** [comment] 2018-04-24 00:13
This is a work in progress, see https://github.com/elastic/kibana/pull/17586

**Comment by nyurik** [comment] 2018-04-24 00:14
duplicate of https://github.com/elastic/kibana/issues/17210

**Closed as completed by nyurik** 2018-04-24 00:14 UTC
Labels: enhancement
